More updates for future-proofing
pypr/cyarray pull request #19
Opened 2024-09-27 10:27 UTC by nauaneed

2024-09-27 10:29 UTC, nauaneed commented
Pysph performance is not tested.

2024-12-13 12:55 UTC, prabhuramachandran requested changes
Please check if this is still compatible with Numpy versions < 2 and fix the silly errors.

2024-12-13 12:55 UTC, prabhuramachandran commented on cyarray/carray.pyx.mako
> +        raise NotImplementedError(BaseArray::reserve')
Please fix this error and the other one.

2024-12-13 17:56 UTC, prabhuramachandran approved these changes
LGTM, thanks.

2024-12-13 17:57 UTC, merged